### ISSUE TITLE
[提案] 埋め込みとかその他のオプション

### ISSUE THREAD

**Issue by InkoHX** [bboyyu51/PM-DiscordAPI#2]
# 提案

DiscordのWebhookはメッセージを送信する以外にも沢山のことができるのでそれらにも対応できると凄い便利になると思います。

https://discordapp.com/developers/docs/resources/webhook#webhook-object-webhook-structure

* 送信した時に表示される名前を変更をできるようにする。
* アバターを変更できるようにする。
* TTSを有効化できるようにする。
* ファイルの送信をできるようにする。
* [埋め込み](https://discordapp.com/developers/docs/resources/channel#embed-object)を使えるようにする。

**Comment by bbo51dog** [comment]
v2.1.0にてembed、アバター、名前、TTSなど対応しました。
ご提案ありがとうございました
