### ISSUE TITLE
例外を投げる

### ISSUE THREAD

**Issue by InkoHX** [bboyyu51/PM-DiscordAPI#3]
APIにリクエストを送った時にエラーが起きることもあるのでエラーコードやその理由をコンソールに表示すると良いと思います。

**Comment by bbo51dog** [comment]
完全に存在忘れてて、すごい今更ですがv3.0.0にて実装しました
ご意見ありがとうございました

**Comment by InkoHX** [comment]
@bbo51dog お疲れ様です！
