### ISSUE TITLE
あなたのプラグインを韓国語に翻訳してもいいですか？

### ISSUE THREAD

**Issue by ghost** [bboyyu51/PM-DiscordAPI#4]
こんにちは私は韓国人の開発者です。
私はあなたのプラグインを韓国語に変換して共有したいと思います。
許していただけますか？

**Comment by bbo51dog** [comment]
返信遅れてすみません
ライセンスに違反しなければ大丈夫です

Sorry for the late reply.
It's ok if you follow the Mit license
